# Generated by Django 2.2.4 on 2019-08-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shieldServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('borrower_name', models.CharField(default='', max_length=255)),
                ('borrower_id', models.CharField(default='', max_length=255)),
                ('borrower_time', models.DateTimeField()),
                ('borrower_sum', models.FloatField()),
                ('borrow_type', models.CharField(default='', max_length=255)),
                ('borrower_phone', models.CharField(default='', max_length=255)),
                ('payback', models.IntegerField()),
                ('payback_time', models.DateTimeField()),
                ('trade_order', models.CharField(default='', max_length=255)),
                ('trade_place', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
