# Generated by Django 2.2.4 on 2019-08-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shieldServer', '0003_auto_20190827_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='should_payback_time',
            field=models.DateTimeField(default='2019-08-28 09:28:30'),
            preserve_default=False,
        ),
    ]
