# Generated by Django 2.2.4 on 2019-08-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shieldServer', '0004_borrower_should_payback_time'),
        ('shieldServer', '0003_auto_20190828_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='is_uploaded',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrower',
            name='funding_terms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
