# Generated by Django 2.2.4 on 2019-08-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shieldServer', '0004_borrower_should_payback_time'),
        ('shieldServer', '0003_auto_20190828_1823'),
    ]

    operations = [
    ]
