# Generated by Django 2.2.4 on 2019-09-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shieldServer', '0006_auto_20190902_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower',
            old_name='vertification_status',
            new_name='verification_status',
        ),
    ]
