# Generated by Django 2.2.4 on 2019-09-03 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shieldServer', '0007_auto_20190902_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='application_type',
        ),
    ]
