# Generated by Django 2.2.4 on 2019-09-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shieldServer', '0008_remove_borrower_application_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='last_pymnt_d',
            field=models.DateTimeField(default=None),
        ),
    ]
