# Generated by Django 2.2.4 on 2019-09-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shieldServer', '0009_auto_20190903_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='total_pymnt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='total_rec_late_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='verification_status',
            field=models.IntegerField(default=1),
        ),
    ]
