# Generated by Django 2.2.4 on 2019-09-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shieldServer', '0010_auto_20190903_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='last_pymnt_d',
            field=models.DateField(default=None),
        ),
    ]
