# Generated by Django 2.2.4 on 2019-09-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shieldServer', '0012_auto_20190903_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='payback_time',
        ),
        migrations.AddField(
            model_name='borrower',
            name='payback',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
