# Generated by Django 2.2.4 on 2019-09-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shieldServer', '0013_auto_20190903_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='last_pymnt_d',
            field=models.DateField(),
        ),
    ]
