# Generated by Django 2.2.4 on 2019-09-05 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shieldServer', '0014_auto_20190903_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='e_credit_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrower',
            name='verification_status',
            field=models.IntegerField(default=-1),
        ),
    ]
