# Generated by Django 2.2.4 on 2019-09-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shieldServer', '0015_auto_20190905_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('loaner_name', models.CharField(default='', max_length=255)),
                ('loaner_id', models.CharField(default='', max_length=255)),
                ('loan_times_insvnd', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
