# Generated by Django 2.2.4 on 2019-09-05 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shieldServer', '0016_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='insert_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
