# Generated by Django 2.2.4 on 2019-09-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shieldServer', '0017_alert_insert_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='month_payback_dt',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrower',
            name='this_month_repay',
            field=models.IntegerField(default=0),
        ),
    ]
