# Generated by Django 2.2.4 on 2019-08-27 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chainServer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='age',
        ),
    ]
