# Generated by Django 2.2.4 on 2019-08-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainServer', '0005_auto_20190828_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordnodes',
            name='ID_card',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recordnodes',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
